[project]
name = "training"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "sentence-transformers>=5.1.0",
    "verifiers[all]>=0.1.3",
    "wordfreq>=3.1.1",
]
[tool.setuptools]
packages = ["src"]